### ISSUE TITLE
CSS Errors

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#1134]
@OmgImAlexis @Thraxis 

any idea how to fix this errors?

![image](https://cloud.githubusercontent.com/assets/2620870/18603589/424e850a-7c49-11e6-9ec0-b4dae8665e51.png)

**Comment by OmgImAlexis** [comment]
The second should be ignored and the top ones are probably missing the ending `}`.

**Comment by fernandog** [comment]
but if you look the code, there are the open {  and the closing } , so don't understand why its missing

```css
.ui-pnotify-container {
    border: 1px solid rgb(17, 17, 17);
    background-image: -moz-linear-gradient(rgb(51, 51, 51), rgb(61, 61, 61)) !important;
    background-image: linear-gradient(rgb(51, 51, 51), rgb(61, 61, 61)) !important;
    background-image: -webkit-linear-gradient(rgb(51, 51, 51), rgb(61, 61, 61)) !important;
    background-image: -o-linear-gradient(rgb(51, 51, 51), rgb(61, 61, 61)) !important;
    filter: progid:dximagetransform.microsoft.gradient(startColorstr=rgb(51, 51, 51), endColorstr=rgb(61, 61, 61)) !important;
    -ms-filter: progid:dximagetransform.microsoft.gradient(startColorstr=rgb(51, 51, 51), endColorstr=rgb(61, 61, 61)) !important;
    -moz-box-shadow: 0 0 2px rgb(0, 0, 0);
    -webkit-box-shadow: 0 0 2px rgb(0, 0, 0);
    -o-box-shadow: 0 0 2px rgb(0, 0, 0);
    box-shadow: 0 0 2px rgb(0, 0, 0);
}

```
