### ISSUE TITLE
[IMPROVEMENT] Don't wrap status column in larger screens

### ISSUE THREAD

**Issue by h3llrais3r** [pymedusa/Medusa#3592]
I find it annoying that the status column is wrapped (i.e. when you have episodes with long names).
What do you think of making it 'no-wrap' for larger screens so the layout becomes more clear (i.e. smaller rows).

AS-IS:
![image](https://user-images.githubusercontent.com/1945295/34738266-cc3fcc34-f578-11e7-95e9-cfc19c8127cc.png)

WITH NO-WRAP:

![image](https://user-images.githubusercontent.com/1945295/34738282-d8a96980-f578-11e7-8380-50a6e9e6a590.png)

What do you think?
Code:
```css
@media screen and (min-width: 769px) {
    td.col-status {
        white-space: nowrap;
    }
}
```

Just need your advise on what the min-width should be... if you agree to change it.
