### ISSUE TITLE
config Profiles

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#661]
I've been working on configuration profiles.
Currently i'm starting with the yaml config, to use the model as a starting point.
I'm interested in everyone's opinions and feedback.

I've chosen for using yaml, because of it's readability.
I'm also working on separate provider configs. Moving all the provider stuff out of config.ini, and into one provider.yaml file. This way we can standardize our provider configs for torrent, usenet, custom torrent, etc. And get rid of all the csv mess.

profile.yaml

``` yaml
settings:
  prioritize_provider: no
profiles:
  -
    name: My profile 1
    id: my_profile_1
    description: A quality profile used on show x,y,z and provider x
    # I want to really create a dynamic configuration
    # Meaning that each profile can apply to a show, or to a provider
    # For example only download 1080WEBDL from providers x an y
    # And download 1080 and 720 from provider z
    enabled_providers:
      -
        provider_id: oznzb
      -
        provider_id: usenet_crawler
      -
        provider_id: hdbits
    # Maybe this isn't the best location for, but currently I can't really
    # think of a better way
    enabled_shows:
      -
        indexer: 1
        indexer_id: 12345
      -
        indexer: 2
        indexer_id: 12344
    quality_options:
      use_quality_options: yes
      root_dir: D:\media\shows
      preferred_quality: 4
      subtitles: no
      status_previous: 3
      status_future: 5
      flatten_folders: no
      is_anime: no
      scene_numbering: yes
      fansub_groups_whitelist:
        - Blablab_Subs
        - HorribleHorrible
        - LALALA
      fansub_groups_blacklist:
        - Really_bullshit
    search_options:
      use_search_options: yes
      enable_daily: yes
      enable_backlog: yes
      enable_manual: yes
      torrent_seed: 0.5
      torrent_minimum_seed: 1
      torrent_minimum_leech: 0
      torrent_freeleech: no
      season_search_mode: episode #can also be season
      season_search_fallback: no
      delay_snatch: yes
      delay_time: 1 hour
      # You can configure a delay on a provider, and configure in the profile,
      # if the provider, should start with it's delay timer, when a show get's
      # its first match on that provider.
      delay_wait_on_provider: oznzb
  # this is the second profile in the list, it's not complete, but this is also
  # just for demo purposses
  -
    name: My profile 2
    id: my_profile_2
    description: A quality profile used on provider y
    enabled_providers:
      - oznzb
      - usenet_crawler
      - hdbits
    enabled_shows:
      -
        indexer: 1
        indexer_id: 12345
      -
        indexer: 2
        indexer_id: 12344
    quality_options:
      use_quality_options: yes
      root_dir: D:\media\shows
      preferred_quality: 4
      subtitles: no
      status_previous: 3
      status_future: 5
      flatten_folders: no
      is_anime: no
      scene_numbering: yes
      fansub_groups_whitelist:
        - Blablab_Subs
        - HorribleHorrible
        - LALALA
      fansub_groups_blacklist:
        - Really_bullshit
    search_options:
      use_search_options: no
      enable_daily: yes
      enable_backlog: yes
      enable_manual: yes
      torrent_seed: 0.5
      torrent_minimum_seed: 1
      torrent_minimum_leech: 0
      torrent_freeleech: no
      season_search_mode: episode #can also be season
      season_search_fallback: no
      delay_snatch: yes
      delay_time: 1 hour
      # You can configure a delay on a provider, and configure in the profile,
      # if the provider, should start with it's delay timer, when a show get's
      # its first match on that provider.
      delay_wait_on_provider: oznzb
```

And a quick provider.yaml example.
Note! This is from python code generated!

``` yaml
providers:
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: NYAATORRENTS
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: TOKYOTOSHOKAN
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: '[LIMETORRENTS'
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: DANISHBITS
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: BITHDTV
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: HD4FREE
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: HOUNDDAWGS
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: HDBITS
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: ABNORMAL
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: ILOVETORRENTS
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: ALPHARATIO
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: SCENETIME
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: BTN
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: RARBG
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: HDSPACE
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: TORRENTBYTES
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: TORRENTZ
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: ELITETORRENT
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: SPEEDCD
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: TNTVILLAGE
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: XTHOR
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: SHAZBAT_TV
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: TORRENTPROJECT
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: BITSNOOP
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: IPTORRENTS
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: EXTRATORRENT
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: MORETHANTV
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: TVCHAOSUK
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: PRETOME
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: TORRENTDAY
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: BTDIGG
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: CPASBIEN
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: SCENEACCESS
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: NEWPCT
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: HDTORRENTS
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: THEPIRATEBAY
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: BLUETIGERS
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: BITCANNON
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: FRESHONTV
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: KICKASSTORRENTS
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: T411
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: TORRENTLEECH
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: TRANSMITTHENET
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: NORBITS
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: GFTRACKER
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: SCENEELITE
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: ZOOQLE
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: USENET_CRAWLER_CUSTOM
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: OZNZB
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: ANIZB
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: WOMBLE_S_INDEX
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: BINSEARCH
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: NZBS_ORG
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: USENET_CRAWLER
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: SPOTWEB
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: NZBGEEK
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: OMGWTFNZBS
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: DOGNZB
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: NZB_CAT
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: NZBs
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
- absolute_numbering: false
  api_key: afdsjflkdsfj32sdfdsfdsf
  cat_ids:
  - 5020
  - 5040
  - 5070
  enable_backlog: false
  enable_daily: false
  enable_manualsearch: false
  enabled: false
  is_newznab: true
  password: my_password
  proper_string:
  - PROPER
  - REPACK
  - REAL
  provider_id: Newzbin
  provider_type: null
  public: false
  search_fallback: false
  search_mode: null
  support_backlog: true
  url: ''
  urls: {}
  username: my_username
settings: []
```
