### ISSUE TITLE
DockerHub Overview contains no setup instructions.

### ISSUE THREAD

**Issue by thesugarat** [pymedusa/Medusa#7995]
Go to Docker Hub page for Medusa. Overview page has no installation instructions. Follow link to installation guides page on github, Click on instructions for  Docker (Official) and get redirected to Docker Hub Overview.

Not a feature request for the software of course, nor is it a bug. But no other place to request this.

I've considered using your official image and using Linuxserver.io's instructions but it's not clear if that would work.

**Comment by nickdex** [comment]
Both images work, I have tested on PopOs (ubuntu) and RaspberryPi (LinuxServer image)

# Docker Compose file 
## Rpi - Medusa + Transmission
Update to `image: pymedusa/medusa` for official
```yaml
version: '2'
services:
  transmission:
    network_mode: 'host'
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - USER=transmission
      - PASS=transmission
    volumes:
      - /home/pi/medusa/transmission:/config
      - /media/Transmission:/downloads
    restart: unless-stopped

  pymedusa:
    network_mode: 'host'
    image: linuxserver/medusa
    container_name: pymedusa
    volumes:
      - /home/pi/medusa/config:/config
      - /media/Transmission:/downloads
      - /tmp:/watch
      - /media/Series:/tv
      - /media/Anime:/anime
    restart: unless-stopped
```
Extra - Use [Portainer](https://github.com/portainer/portainer/) to manage docker related stuff
